language: c

matrix:
  include:
   - os: linux
     dist: trusty
   - os: linux
     dist: xenial
   - os: windows
   - os: osx


script:
  - gcc -o detecter detecter.c
  - ./detecter -c -i 10000 -l 4 -t "%H:%M:%S" ls -l /tmp
