language: c

matrix:
  include:
   - os: linux
     dist: trusty
   - os: linux
     dist: xenial
   - os: windows
   - os: osx

addons:
  apt:
    packages:
      - gcovr
      - libcunit1-dev

  homebrew:
    packages:
      - cunit
      - gcovr

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      echo "Using LINUX" ;
    fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "Using MAC OS/X" ;
    fi
  - ./detecter -c -i 10000 -l 4 -t "%H:%M:%S" ls -l /tmp
